"""sprint5_anomaly_detection

Revision ID: 1c270496bd72
Revises: 4ea56f925700
Create Date: 2026-06-12 20:43:51.447544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c270496bd72'
down_revision: Union[str, None] = '4ea56f925700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('total_amount_sum', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('std_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('last_invoice_date', sa.Date(), nullable=True),
    sa.Column('first_seen_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_risk_scores_supplier_name'), 'supplier_risk_scores', ['supplier_name'], unique=True)
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.Enum('ABNORMAL_AMOUNT', 'NEW_HIGH_RISK_SUPPLIER', 'PRICE_SPIKE', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACKNOWLEDGED', 'DISMISSED', name='alert_status'), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alerts_invoice_id'), 'anomaly_alerts', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_alerts_invoice_id'), table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    op.drop_index(op.f('ix_supplier_risk_scores_supplier_name'), table_name='supplier_risk_scores')
    op.drop_table('supplier_risk_scores')
    # ### end Alembic commands ###
