"""add_has_duplicate_alert

Revision ID: 4ea56f925700
Revises: a72f9fa0999e
Create Date: 2026-06-12 19:23:11.592348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea56f925700'
down_revision: Union[str, None] = 'a72f9fa0999e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('has_duplicate_alert', sa.Boolean(), nullable=True))
    op.execute("UPDATE invoices SET has_duplicate_alert = FALSE WHERE has_duplicate_alert IS NULL")
    op.alter_column('invoices', 'has_duplicate_alert', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'has_duplicate_alert')
    # ### end Alembic commands ###
