"""add_has_anomaly_alert

Revision ID: 837fc7498ad5
Revises: 1c270496bd72
Create Date: 2026-06-12 20:45:12.638841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837fc7498ad5'
down_revision: Union[str, None] = '1c270496bd72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('has_anomaly_alert', sa.Boolean(), server_default=sa.text('false')))
    op.alter_column('invoices', 'has_anomaly_alert', nullable=False)
    op.alter_column('invoices', 'has_anomaly_alert', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'has_anomaly_alert')
    # ### end Alembic commands ###
