"""sprint4_duplicate_detection

Revision ID: a72f9fa0999e
Revises: a88dde233b19
Create Date: 2026-06-12 19:19:52.611850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72f9fa0999e'
down_revision: Union[str, None] = 'a88dde233b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('matched_invoice_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT_NUMBER', 'FUZZY_SIMILARITY', name='match_type'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED_DUPLICATE', 'REJECTED', name='duplicate_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'matched_invoice_id')
    )
    op.create_index(op.f('ix_duplicate_matches_invoice_id'), 'duplicate_matches', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_duplicate_matches_matched_invoice_id'), 'duplicate_matches', ['matched_invoice_id'], unique=False)
    op.add_column('invoices', sa.Column('is_duplicate_confirmed', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('has_duplicate_alert', sa.Boolean(), nullable=True))
    op.execute("UPDATE invoices SET is_duplicate_confirmed = FALSE, has_duplicate_alert = FALSE WHERE is_duplicate_confirmed IS NULL")
    op.alter_column('invoices', 'is_duplicate_confirmed', nullable=False)
    op.alter_column('invoices', 'has_duplicate_alert', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'has_duplicate_alert')
    op.drop_column('invoices', 'is_duplicate_confirmed')
    op.drop_index(op.f('ix_duplicate_matches_matched_invoice_id'), table_name='duplicate_matches')
    op.drop_index(op.f('ix_duplicate_matches_invoice_id'), table_name='duplicate_matches')
    op.drop_table('duplicate_matches')
    # ### end Alembic commands ###
