"""initial_sprint1_sprint2_sprint3

Revision ID: a88dde233b19
Revises: 006_invoice_ocr_tracking
Create Date: 2026-06-12 15:38:50.320522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a88dde233b19'
down_revision: Union[str, None] = '006_invoice_ocr_tracking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
